# Generated by Django 6.1 on 2026-08-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('food_type', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non_Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.PositiveBigIntegerField()),
                ('unit', models.CharField(default='meals', max_length=30)),
                ('avaliable_from', models.DateTimeField()),
                ('avaliable_until', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Avaliable'), ('RESERVED', 'Reserved'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
