# Generated by Django 6.1 on 2026-08-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiy', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='food.foodlisting')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
