# Generated by Django 6.1 on 2026-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
