# Generated by Django 6.1 on 2026-08-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodreservation_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreservation',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
