# Generated by Django 6.1 on 2026-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_quantiy_foodreservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Avaliable'), ('FULLY_RESERVED', 'Fully Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20),
        ),
    ]
