# Generated by Django 6.1 on 2026-08-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodlisting_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlisting',
            old_name='avaliable_from',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='foodlisting',
            old_name='avaliable_until',
            new_name='available_until',
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('FULLY_RESERVED', 'Fully Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20),
        ),
    ]
